// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/data/repositories/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/core/error_handling/result.dart' as _i4;
import 'package:flower_app/features/auth/data/data_source/auth_data_source_impl.dart'
    as _i2;
import 'package:flower_app/features/auth/data/models/requests/login_request.dart'
    as _i6;
import 'package:flower_app/features/auth/data/models/requests/reset_password_request.dart'
    as _i9;
import 'package:flower_app/features/auth/data/models/requests/send_reset_password_code_request.dart'
    as _i13;
import 'package:flower_app/features/auth/data/models/requests/signup_request.dart'
    as _i11;
import 'package:flower_app/features/auth/data/models/requests/verify_reset_code_request.dart'
    as _i15;
import 'package:flower_app/features/auth/data/models/response/login_response.dart'
    as _i5;
import 'package:flower_app/features/auth/data/models/response/reset_password_response.dart'
    as _i8;
import 'package:flower_app/features/auth/data/models/response/send_reset_password_code_response.dart'
    as _i12;
import 'package:flower_app/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i14;
import 'package:flower_app/features/auth/data/models/user_dto.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDataSourceImpl extends _i1.Mock
    implements _i2.AuthDataSourceImpl {
  MockAuthDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.LoginResponse>> login({
    required _i6.LoginRequest? loginRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequest: loginRequest}),
            returnValue: _i3.Future<_i4.Result<_i5.LoginResponse>>.value(
              _i7.dummyValue<_i4.Result<_i5.LoginResponse>>(
                this,
                Invocation.method(#login, [], {#loginRequest: loginRequest}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.LoginResponse>>);

  @override
  _i3.Future<_i4.Result<_i8.ResetPasswordResponse>> resetPassword({
    required _i9.ResetPasswordRequest? resetPasswordRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequest: resetPasswordRequest,
            }),
            returnValue:
                _i3.Future<_i4.Result<_i8.ResetPasswordResponse>>.value(
                  _i7.dummyValue<_i4.Result<_i8.ResetPasswordResponse>>(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #resetPasswordRequest: resetPasswordRequest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.ResetPasswordResponse>>);

  @override
  _i3.Future<_i4.Result<_i10.UserDto>> signup({
    required _i11.SignupRequest? signupRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {#signupRequest: signupRequest}),
            returnValue: _i3.Future<_i4.Result<_i10.UserDto>>.value(
              _i7.dummyValue<_i4.Result<_i10.UserDto>>(
                this,
                Invocation.method(#signup, [], {#signupRequest: signupRequest}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i10.UserDto>>);

  @override
  _i3.Future<_i4.Result<_i12.SendResetPasswordCodeResponse>>
  sendResetPasswordCode({
    required _i13.SendResetPasswordCodeRequest? sendResetPasswordCodeRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetPasswordCode, [], {
              #sendResetPasswordCodeRequest: sendResetPasswordCodeRequest,
            }),
            returnValue:
                _i3.Future<
                  _i4.Result<_i12.SendResetPasswordCodeResponse>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i12.SendResetPasswordCodeResponse>
                  >(
                    this,
                    Invocation.method(#sendResetPasswordCode, [], {
                      #sendResetPasswordCodeRequest:
                          sendResetPasswordCodeRequest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i12.SendResetPasswordCodeResponse>>);

  @override
  _i3.Future<_i4.Result<_i14.VerifyResetCodeResponse>> verifyResetPasswordCode({
    required _i15.VerifyResetCodeRequest? verifyResetCodeRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetPasswordCode, [], {
              #verifyResetCodeRequest: verifyResetCodeRequest,
            }),
            returnValue:
                _i3.Future<_i4.Result<_i14.VerifyResetCodeResponse>>.value(
                  _i7.dummyValue<_i4.Result<_i14.VerifyResetCodeResponse>>(
                    this,
                    Invocation.method(#verifyResetPasswordCode, [], {
                      #verifyResetCodeRequest: verifyResetCodeRequest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i14.VerifyResetCodeResponse>>);
}
